spring.application.name=order-service
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5435/innowise_order_service_db
spring.datasource.username=order_user
spring.datasource.password=order_pass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.user=order_user
spring.liquibase.password=order_pass

user-service.url=http://localhost:8082

server.port=8083

spring.kafka.bootstrap-servers=localhost:9092
kafka.topics.order-created=order-created-topic
kafka.topics.payment-created=payment-created-topic

# Enable detailed logging
logging.level.com.example.tasks.orderservice=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

# Show SQL with parameters
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Show validation errors
logging.level.org.springframework.web=INFO
logging.level.org.springframework.transaction=INFO