spring.application.name=order-service
spring.docker.compose.enabled=false

# Docker environment database connection
spring.datasource.url=jdbc:postgresql://order-service-postgres:5432/orderdb
spring.datasource.username=order_user
spring.datasource.password=order_pass

# Docker environment Kafka connection
spring.kafka.bootstrap-servers=order-payment-kafka:9093
kafka.topics.order-created=order-created-topic
kafka.topics.payment-created=payment-created-topic

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.user=order_user
spring.liquibase.password=order_pass

user-service.url=http://user-service:8082

server.port=8083